name: Build JUCE Plugin on macOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up CMake
      uses: actions/setup-cmake@v3
      with:
        cmake-version: '3.21'  # specify the version you need

    - name: Install Xcode Command Line Tools
      run: xcode-select --install

    - name: Install dependencies
      run: |
        brew install cmake
        brew install ninja

    - name: Configure and Build Plugin
      run: |
        mkdir -p build
        cd build
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=../JUCE/extras/cmake/Modules/juce_toolchain.cmake ..
        ninja

    - name: Archive Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: vst3-plugin
        path: build/YourPluginName.vst3
